export let NullCourse = {
    "terms": [
        {
            "termID": 706,
            "termName": "Q1",
            "termScheduleID": 256,
            "termScheduleName": "Quarters",
            "termSeq": 1,
            "isPrimary": true,
            "startDate": "2022-08-17",
            "endDate": "2022-10-14"
        },
        {
            "termID": 707,
            "termName": "Q2",
            "termScheduleID": 256,
            "termScheduleName": "Quarters",
            "termSeq": 2,
            "isPrimary": true,
            "startDate": "2022-10-17",
            "endDate": "2022-12-22"
        },
        {
            "termID": 708,
            "termName": "Q3",
            "termScheduleID": 256,
            "termScheduleName": "Quarters",
            "termSeq": 3,
            "isPrimary": true,
            "startDate": "2023-01-09",
            "endDate": "2023-03-16"
        },
        {
            "termID": 709,
            "termName": "Q4",
            "termScheduleID": 256,
            "termScheduleName": "Quarters",
            "termSeq": 4,
            "isPrimary": true,
            "startDate": "2023-03-20",
            "endDate": "2023-06-02"
        }
    ],
    "details": [
        {
            "task": {
                "_id": "12157",
                "personID": 12157,
                "trialID": 1295,
                "calendarID": 725,
                "structureID": 721,
                "courseID": 29623,
                "courseName": "Playground",
                "sectionID": 379630,
                "taskID": 2,
                "termID": 706,
                "hasAssignments": false,
                "hasCompositeTasks": false,
                "taskName": "Quarter Grade",
                "gradedOnce": false,
                "treeTraversalSeq": 2,
                "hasDetail": false,
                "_model": "PortalGradingTaskModel",
                "_hashCode": "410452639",
                "termName": "Q1",
                "termSeq": 1
            },
            "categories": [],
            "children": null
        },
        {
            "task": {
                "_id": "12157",
                "personID": 12157,
                "trialID": 1295,
                "calendarID": 725,
                "structureID": 721,
                "courseID": 29623,
                "courseName": "Playground",
                "sectionID": 379630,
                "taskID": 3,
                "termID": 706,
                "hasAssignments": false,
                "hasCompositeTasks": false,
                "taskName": "Mid-Term Grade",
                "gradedOnce": false,
                "treeTraversalSeq": 3,
                "hasDetail": false,
                "_model": "PortalGradingTaskModel",
                "_hashCode": "1956266458",
                "termName": "Q1",
                "termSeq": 1
            },
            "categories": [],
            "children": null
        },
        {
            "task": {
                "_id": "12157",
                "personID": 12157,
                "trialID": 1295,
                "calendarID": 725,
                "structureID": 721,
                "courseID": 29623,
                "courseName": "Playground",
                "sectionID": 379630,
                "taskID": 1,
                "termID": 707,
                "hasAssignments": false,
                "hasCompositeTasks": true,
                "taskName": "Semester Final",
                "gradedOnce": false,
                "treeTraversalSeq": 1,
                "hasDetail": true,
                "_model": "PortalGradingTaskModel",
                "_hashCode": "1765994671",
                "termName": "Q2",
                "termSeq": 2
            },
            "categories": [],
            "children": [
                {
                    "_id": "12157",
                    "personID": 12157,
                    "trialID": 1295,
                    "calendarID": 725,
                    "structureID": 721,
                    "courseID": 29623,
                    "courseName": "Playground",
                    "sectionID": 379630,
                    "taskID": 2,
                    "termID": 707,
                    "hasAssignments": false,
                    "hasCompositeTasks": false,
                    "taskName": "Quarter Grade",
                    "gradedOnce": false,
                    "treeTraversalSeq": 2,
                    "calculationWeight": 100,
                    "calculationPercent": 1,
                    "hasDetail": false,
                    "_model": "PortalGradingTaskModel",
                    "_hashCode": "-1666756704",
                    "termName": "Q2",
                    "termSeq": 2
                }
            ]
        },
        {
            "task": {
                "_id": "12157",
                "personID": 12157,
                "trialID": 1295,
                "calendarID": 725,
                "structureID": 721,
                "courseID": 29623,
                "courseName": "Playground",
                "sectionID": 379630,
                "taskID": 2,
                "termID": 707,
                "hasAssignments": false,
                "hasCompositeTasks": false,
                "taskName": "Quarter Grade",
                "gradedOnce": false,
                "treeTraversalSeq": 2,
                "calculationWeight": 100,
                "calculationPercent": 1,
                "hasDetail": false,
                "_model": "PortalGradingTaskModel",
                "_hashCode": "-1666756704",
                "termName": "Q2",
                "termSeq": 2
            },
            "categories": [],
            "children": null
        },
        {
            "task": {
                "_id": "12157",
                "personID": 12157,
                "trialID": 1295,
                "calendarID": 725,
                "structureID": 721,
                "courseID": 29623,
                "courseName": "Playground",
                "sectionID": 379630,
                "taskID": 3,
                "termID": 707,
                "hasAssignments": false,
                "hasCompositeTasks": false,
                "taskName": "Mid-Term Grade",
                "gradedOnce": false,
                "treeTraversalSeq": 3,
                "hasDetail": false,
                "_model": "PortalGradingTaskModel",
                "_hashCode": "-120942885",
                "termName": "Q2",
                "termSeq": 2
            },
            "categories": [],
            "children": null
        },
        {
            "task": {
                "_id": "12157",
                "personID": 12157,
                "trialID": 1295,
                "calendarID": 725,
                "structureID": 721,
                "courseID": 29623,
                "courseName": "Playground",
                "sectionID": 379630,
                "taskID": 2,
                "termID": 708,
                "hasAssignments": false,
                "hasCompositeTasks": false,
                "taskName": "Quarter Grade",
                "gradedOnce": false,
                "treeTraversalSeq": 2,
                "hasDetail": false,
                "_model": "PortalGradingTaskModel",
                "_hashCode": "551001249",
                "termName": "Q3",
                "termSeq": 3
            },
            "categories": [],
            "children": null
        },
        {
            "task": {
                "_id": "12157",
                "personID": 12157,
                "trialID": 1295,
                "calendarID": 725,
                "structureID": 721,
                "courseID": 29623,
                "courseName": "Playground",
                "sectionID": 379630,
                "taskID": 3,
                "termID": 708,
                "hasAssignments": false,
                "hasCompositeTasks": false,
                "taskName": "Mid-Term Grade",
                "gradedOnce": false,
                "treeTraversalSeq": 3,
                "hasDetail": false,
                "_model": "PortalGradingTaskModel",
                "_hashCode": "2096815068",
                "termName": "Q3",
                "termSeq": 3
            },
            "categories": [],
            "children": null
        },
        {
            "task": {
                "_id": "12157",
                "personID": 12157,
                "trialID": 1295,
                "calendarID": 725,
                "structureID": 721,
                "courseID": 29623,
                "courseName": "Playground",
                "sectionID": 379630,
                "taskID": 1,
                "termID": 709,
                "hasAssignments": false,
                "hasCompositeTasks": true,
                "taskName": "Semester Final",
                "gradedOnce": false,
                "treeTraversalSeq": 1,
                "hasDetail": true,
                "_model": "PortalGradingTaskModel",
                "_hashCode": "1906543281",
                "termName": "Q4",
                "termSeq": 4
            },
            "categories": [],
            "children": [
                {
                    "_id": "12157",
                    "personID": 12157,
                    "trialID": 1295,
                    "calendarID": 725,
                    "structureID": 721,
                    "courseID": 29623,
                    "courseName": "Playground",
                    "sectionID": 379630,
                    "taskID": 2,
                    "termID": 709,
                    "hasAssignments": false,
                    "hasCompositeTasks": false,
                    "taskName": "Quarter Grade",
                    "gradedOnce": false,
                    "treeTraversalSeq": 2,
                    "calculationWeight": 100,
                    "calculationPercent": 1,
                    "hasDetail": false,
                    "_model": "PortalGradingTaskModel",
                    "_hashCode": "-1526208094",
                    "termName": "Q4",
                    "termSeq": 4
                }
            ]
        },
        {
            "task": {
                "_id": "12157",
                "personID": 12157,
                "trialID": 1295,
                "calendarID": 725,
                "structureID": 721,
                "courseID": 29623,
                "courseName": "Playground",
                "sectionID": 379630,
                "taskID": 2,
                "termID": 709,
                "hasAssignments": false,
                "hasCompositeTasks": false,
                "taskName": "Quarter Grade",
                "gradedOnce": false,
                "treeTraversalSeq": 2,
                "calculationWeight": 100,
                "calculationPercent": 1,
                "hasDetail": false,
                "_model": "PortalGradingTaskModel",
                "_hashCode": "-1526208094",
                "termName": "Q4",
                "termSeq": 4
            },
            "categories": [],
            "children": null
        },
        {
            "task": {
                "_id": "12157",
                "personID": 12157,
                "trialID": 1295,
                "calendarID": 725,
                "structureID": 721,
                "courseID": 29623,
                "courseName": "Playground",
                "sectionID": 379630,
                "taskID": 3,
                "termID": 709,
                "hasAssignments": false,
                "hasCompositeTasks": false,
                "taskName": "Mid-Term Grade",
                "gradedOnce": false,
                "treeTraversalSeq": 3,
                "hasDetail": false,
                "_model": "PortalGradingTaskModel",
                "_hashCode": "19605725",
                "termName": "Q4",
                "termSeq": 4
            },
            "categories": [],
            "children": null
        }
    ]
}